% --- Basic information about h5 files generated by MultiChannel Systems
% software suite and recording system

function [rate, durSec, label, exponent, conv, info] = h5fileinfo(filename)

% Metadata on file
info = h5info(filename);

% Duration
dur = h5readatt(filename, '/Data/Recording_0', 'Duration');     % µs
durSec = double(dur)*1e-6;      % s

% Info channel: electrode labels, exponent for voltage data, conversion
% factor, sampling rate [Hz]
h5path = info.Groups.Groups.Groups(1).Groups.Name;
infoCh = h5read(filename, [h5path, '/InfoChannel']);
label = infoCh.Label;
exponent = infoCh.Exponent(1);
conv = double(infoCh.ConversionFactor(1));
rate = 1/(double(infoCh.Tick(1))*1e-6);     % Hz